SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS sakila_dwh;
CREATE SCHEMA sakila_dwh;
USE sakila_dwh;

--
-- Table structure for table 'QUIENCORRE'
--

CREATE TABLE QUIENCORRE (
  qc_id 				SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  edad 					DECIMAL(6,3) UNSIGNED NOT NULL,
  sexo					VARCHAR(1),
  peso					DECIMAL(6,3),
  altura				DECIMAL(6,3),
  anhos_experiencia		DECIMAL(6,3),
  last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY			(qc_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'QUECOCHE'
--

CREATE TABLE QUECOCHE (
  qcoche_id			SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  n_total_pruebas	SMALLINT UNSIGNED NOT NULL,
  ancho				DECIMAL(4,2),
  largo 			DECIMAL(4,2),
  potencia			DECIMAL(5,2),
  vel_max			DECIMAL(5,2),
  last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY		(qcoche_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'CUANDOCORRE'
--

CREATE TABLE CUANDOCORRE (
  cc_id		SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  anho		YEAR DEFAULT NULL,
  trimestre	SMALLINT,
  mes		VARCHAR(20),
  semana	SMALLINT,
  dia		SMALLINT,
  last_update 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY	(cc_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'QUIENPATROCINA'
--

CREATE TABLE QUIENPATROCINA (
  qp_id					SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre				VARCHAR(20),
  dur_contrato			SMALLINT UNSIGNED NOT NULL,
  dinero_patrocinio		DECIMAL(10,2),
  last_update 			TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY			(qp_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'DONDECORRE'
--

CREATE TABLE DONDECORRE (
  dc_id			SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  n_curvas		VARCHAR(7),
  meteorologia	VARCHAR(10),
  nombre		VARCHAR(20),
  pais			VARCHAR(20),
  ciudad		VARCHAR(20),
  last_update 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY			(dc_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table 'RENDIMIENTO'
--

CREATE TABLE RENDIMIENTO (
  rendimiento_id  SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  num_vueltas SMALLINT,
  dinero_patrocinio DECIMAL(12,2),
  porcentaje_pruebas_exitosas SMALLINT UNSIGNED NOT NULL,
  mejores_vueltas SMALLINT UNSIGNED NOT NULL, 
  qc_id SMALLINT UNSIGNED NOT NULL,
  qcoche_id SMALLINT UNSIGNED NOT NULL,
  cc_id SMALLINT UNSIGNED NOT NULL,
  qp_id SMALLINT UNSIGNED NOT NULL,
  dc_id SMALLINT UNSIGNED NOT NULL,
  last_update 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY			(rendimiento_id),
  KEY 					fk_quiencorre(qc_id),
  KEY 					fk_quecochecorre(qcoche_id),
  KEY 					fk_cuandocorre(cc_id),
  KEY 					fk_dondecorre(dc_id),
  KEY 					fk_quienpatrocina(qp_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
